POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name": "Abhishek Raj",
  "username": "abhishekraj",
  "email": "abhi@test.com",
  "password": "123456"
}


###
POST http://localhost:5000/api/user/login
Content-Type: application/json  

{
  "email": "abhi@test.com",
  "password": "123456"
}


###
GET http://localhost:5000/api/user/profile
Content-Type: application/json  

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWExODU2NjIzMzRhMDg4MWU0MDE3NiIsImVtYWlsIjoiYWJoaUB0ZXN0LmNvbSIsImlhdCI6MTc1NTk3ODAyNywiZXhwIjoxNzU1OTgxNjI3fQ.YZLOVUahHd8k52r6mBYn4mJgafY3KpdQuFpNDSqehrs"
}



###
POST http://localhost:5000/api/forms/contact
Content-Type: application/json

{
  "name": "Abhishek",
  "email": "ab3i@test.com",
  "phone": "9876533210",
  "message": "Hello bhai!"
}


###
GET http://localhost:5000/api/forms/contact
Content-Type: application/json

###
POST http://localhost:5000/api/forms/organization
Content-Type: application/json

{
  "name": "CodRexa Solutions",
  "email": "contact@codrexa.com",
  "phone": "9876501234",
  "company": "CodRexa Pvt Ltd",
  "location": "Delhi",
  "Service": "Mobile App Development",
  "url": "https://codrexa.com",
  "requirement": "We need a cross-platform mobile app"
}



###
GET http://localhost:5000/api/forms/organization
Content-Type: application/json


###
POST http://localhost:5000/api/forms/personal
Content-Type: application/json

{
  "name": "Abhishek Raj",
  "email": "abhi@test.com",
  "phone": "9876543210",
  "location": "Patna",
  "requirement": "Need home tutoring"
}


###
GET http://localhost:5000/api/forms/personal
Content-Type: application/json



